// minimal header for linking a byte array of shellcode

#pragma once

#include <windows.h>
#include <winternl.h>

// caller must define this array (generated by the converter)
extern unsigned char shellcode[];
extern const size_t shellcodeSize;

// helper typedef; kept here so both x86/x64 code have it available
typedef NTSTATUS(WINAPI* NTQUERYINFOPROC64)(
    HANDLE           ProcessHandle,
    PROCESSINFOCLASS ProcessInformationClass,
    PVOID            ProcessInformation,
    ULONG            ProcessInformationLength,
    PULONG_PTR       ReturnLength
    );
