#include "converter.h"

#include <fstream>
#include <iomanip>

bool ReadBinaryFile(const std::filesystem::path& inputPath, std::vector<unsigned char>& output, std::wstring& error) {
    std::ifstream file(inputPath, std::ios::binary);
    if (!file) {
        error = L"Unable to open input file.";
        return false;
    }

    output.assign(std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>());
    if (!file.good() && !file.eof()) {
        error = L"Read error while loading input file.";
        return false;
    }

    return true;
}

bool WriteShellcodeHeader(
    const std::filesystem::path& outputPath,
    const std::vector<unsigned char>& data,
    const std::string& symbolName,
    const std::string& sizeSymbolName,
    size_t bytesPerLine,
    std::wstring& error) {
    if (bytesPerLine == 0) {
        error = L"bytesPerLine must be greater than zero.";
        return false;
    }

    std::ofstream outputFile(outputPath, std::ios::trunc);
    if (!outputFile) {
        error = L"Failed to create output file.";
        return false;
    }

    outputFile << "// generated by shellcode-converter\n";
    outputFile << "#include <cstddef>\n\n";
    outputFile << "unsigned char " << symbolName << "[" << data.size() << "] = {\n";

    for (size_t i = 0; i < data.size(); ++i) {
        if (i % bytesPerLine == 0) {
            outputFile << "    ";
        }

        outputFile << "0x"
                   << std::uppercase
                   << std::hex
                   << std::setw(2)
                   << std::setfill('0')
                   << static_cast<int>(data[i]);

        if (i + 1 != data.size()) {
            outputFile << ", ";
        }

        if ((i + 1) % bytesPerLine == 0 || i + 1 == data.size()) {
            outputFile << "\n";
        }
    }

    outputFile << "};\n";
    outputFile << "const size_t " << sizeSymbolName << " = " << data.size() << ";\n";

    if (!outputFile.good()) {
        error = L"Failed while writing output file.";
        return false;
    }

    return true;
}
