#include <iostream>
#include <fstream>
#include <iomanip>
#include <vector>
#include <windows.h>
#include <filesystem>
#include <locale>
#include <codecvt>

std::string openFileDialog() {
    OPENFILENAME ofn;
    char szFile[260] = { 0 };

    ZeroMemory(&ofn, sizeof(ofn));
    ofn.lStructSize = sizeof(ofn);
    ofn.hwndOwner = NULL;
    ofn.lpstrFile = szFile;
    ofn.lpstrFile[0] = '\0';
    ofn.nMaxFile = sizeof(szFile);
    ofn.lpstrFilter = "All Files\0*.*\0";
    ofn.nFilterIndex = 1;
    ofn.Flags = OFN_PATHMUSTEXIST | OFN_FILEMUSTEXIST;

    if (GetOpenFileName(&ofn) == TRUE) {
        return std::string(szFile);
    }
    else {
        return "";
    }
}

// return a path to the input file selected by the user or an empty string if
// the dialog was cancelled.  We use the `OPENFILENAMEW` variant so the code is
// unicode‑aware and can handle paths with non-ASCII characters.

int main(int argc, wchar_t* argv[]) {
    std::wstring inputPath;
    if (argc > 1) {
        // allow the caller to specify an executable on the command line for
        // simple scripting or quick tests
        inputPath = argv[1];
    } else {
        std::string temp = openFileDialog();
        if (temp.empty()) {
            std::cerr << "No file selected.\n";
            return 1;
        }
        inputPath.assign(temp.begin(), temp.end());
    }

    std::filesystem::path exePath = inputPath;
    if (!std::filesystem::exists(exePath)) {
        std::cerr << "Input file does not exist: " << std::wstring_convert<std::codecvt_utf8<wchar_t>>().to_bytes(exePath.wstring()) << "\n";
        return 1;
    }

    std::vector<unsigned char> buffer;
    {
        std::ifstream file(exePath, std::ios::binary);
        if (!file) {
            std::cerr << "Unable to open " << exePath.u8string() << "\n";
            return 1;
        }
        buffer.assign(std::istreambuf_iterator<char>(file), {});
    }

    std::filesystem::path outPath = exePath.parent_path() / "shellcode.h";
    std::ofstream outputFile(outPath, std::ios::trunc);
    if (!outputFile) {
        std::cerr << "Failed to create output file: " << outPath.u8string() << "\n";
        return 1;
    }

    outputFile << "// generated by shellcode-converter\n";
    outputFile << "unsigned char shellcode[" << buffer.size() << "] = {\n";

    for (size_t i = 0; i < buffer.size(); ++i) {
        if (i % 16 == 0) outputFile << "    ";
        outputFile << "0x" << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(buffer[i]);
        if (i + 1 != buffer.size()) outputFile << ", ";
        if ((i + 1) % 16 == 0 || i + 1 == buffer.size()) outputFile << "\n";
    }

    outputFile << "};\n";
    outputFile << "const size_t shellcodeSize = " << buffer.size() << ";\n";

    std::cout << "Shellcode written to " << outPath.u8string() << "\n";
    return 0;
}
